spark-app-basis:
  kubeflow:
    sparkOperator:
      serviceAccount: <no value>
      namespace: <no value>

  spark:
    driver:
      cores: <no value>
      memory: "<no value>"
    executor:
      instances: <no value>
      cores: <no value>
      memory: "<no value>"
