apiVersion: v2
name: spark-data-pipeline
version: 0.0.1
files:
- src/**
dependencies:
  - name: spark-app-basis
    version: 0.0.1
    repository: "file:///Users/alexsergeenko/Documents/Projects/Neoflex/spark/spark-app-base"
    condition: spark-app.enable
