subjectArea: batch-model-inference
spark-app-basis:
  global:
    parentChart:
      name: <no value>   
      version: <no value>
      appVersion: <no value>
      subjectArea: batch-model-inference
  spark:
    mainApplicationFilename: "main.py"
    ui:
      port: 4045
