{{- /* Сбор файлов из директории src */}}
{{- $files := dict }}
{{- range $path, $_ := .Files.Glob "src/**" }}
  {{- $key := $path | trimPrefix "src/" | replace "/" "_" }}
  {{- $content := $.Files.Get $path }}
  {{- $files = set $files $key $content }}
{{- end }}

{{- /* Вызов шаблона из базового чарта */}}
{{- include "spark-app-base.configmap-code" (dict "Release" .Release "files" $files) }}
